### ISSUE TITLE
[Deploy] 서버 배포환경 구축

### ISSUE THREAD

**Issue by chanhyeokseo** [Central-MakeUs/DayCarat-Server#1]
# 서버 배포환경 구축

> [!IMPORTANT]
> 비용 문제로 EC2 배포 환경으로 변경하였습니다. (업데이트한 인프라 구조도는 추후 업로드 예정)

![image](https://github.com/Central-MakeUs/DayCarat-Server/assets/76674422/bc4dbd77-c081-407f-81d0-559183e57106)

- 컨테이너 서비스로 ECS를 채택하여 private subnet에서의 CI/CD를 가능하게 구현
- VPC Endpoint와 S3 event stream을 통한 외부 API로의 internet connectivity

# Tasks
- [x] VPC 환경 구성
- [x] ECS Task Definition / ECS Service / ECS Task 정상 작동 확인 
- [x] ALB / Route 53 / Certificate Manager (개발 환경 구성)
- [x] ECR 이미지 배포 -> ECS 빌드 자동화 (CICD 구현)
- [x] CloudWatch -> Slack API -> 에러 로그 전송 자동화
- [x] S3 -> SQS -> Lambda 이벤트 스트림
